/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package serviceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the assetlistentry service. Represents a row in the &quot;LT_assetlistentry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>serviceBuilder.model.impl.assetlistentryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>serviceBuilder.model.impl.assetlistentryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see assetlistentry
 * @generated
 */
@ProviderType
public interface assetlistentryModel extends BaseModel<assetlistentry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assetlistentry model instance should use the {@link assetlistentry} interface instead.
	 */

	/**
	 * Returns the primary key of this assetlistentry.
	 *
	 * @return the primary key of this assetlistentry
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this assetlistentry.
	 *
	 * @param primaryKey the primary key of this assetlistentry
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this assetlistentry.
	 *
	 * @return the uuid of this assetlistentry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this assetlistentry.
	 *
	 * @param uuid the uuid of this assetlistentry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the mvccversion of this assetlistentry.
	 *
	 * @return the mvccversion of this assetlistentry
	 */
	public int getMvccversion();

	/**
	 * Sets the mvccversion of this assetlistentry.
	 *
	 * @param mvccversion the mvccversion of this assetlistentry
	 */
	public void setMvccversion(int mvccversion);

	/**
	 * Returns the ctcollectionid of this assetlistentry.
	 *
	 * @return the ctcollectionid of this assetlistentry
	 */
	public int getCtcollectionid();

	/**
	 * Sets the ctcollectionid of this assetlistentry.
	 *
	 * @param ctcollectionid the ctcollectionid of this assetlistentry
	 */
	public void setCtcollectionid(int ctcollectionid);

	/**
	 * Returns the assetlistentryid of this assetlistentry.
	 *
	 * @return the assetlistentryid of this assetlistentry
	 */
	public int getAssetlistentryid();

	/**
	 * Sets the assetlistentryid of this assetlistentry.
	 *
	 * @param assetlistentryid the assetlistentryid of this assetlistentry
	 */
	public void setAssetlistentryid(int assetlistentryid);

	/**
	 * Returns the groupid of this assetlistentry.
	 *
	 * @return the groupid of this assetlistentry
	 */
	public int getGroupid();

	/**
	 * Sets the groupid of this assetlistentry.
	 *
	 * @param groupid the groupid of this assetlistentry
	 */
	public void setGroupid(int groupid);

	/**
	 * Returns the companyid of this assetlistentry.
	 *
	 * @return the companyid of this assetlistentry
	 */
	public int getCompanyid();

	/**
	 * Sets the companyid of this assetlistentry.
	 *
	 * @param companyid the companyid of this assetlistentry
	 */
	public void setCompanyid(int companyid);

	/**
	 * Returns the userid of this assetlistentry.
	 *
	 * @return the userid of this assetlistentry
	 */
	public int getUserid();

	/**
	 * Sets the userid of this assetlistentry.
	 *
	 * @param userid the userid of this assetlistentry
	 */
	public void setUserid(int userid);

	/**
	 * Returns the username of this assetlistentry.
	 *
	 * @return the username of this assetlistentry
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this assetlistentry.
	 *
	 * @param username the username of this assetlistentry
	 */
	public void setUsername(String username);

	/**
	 * Returns the createdate of this assetlistentry.
	 *
	 * @return the createdate of this assetlistentry
	 */
	public Date getCreatedate();

	/**
	 * Sets the createdate of this assetlistentry.
	 *
	 * @param createdate the createdate of this assetlistentry
	 */
	public void setCreatedate(Date createdate);

	/**
	 * Returns the modifieddate of this assetlistentry.
	 *
	 * @return the modifieddate of this assetlistentry
	 */
	public Date getModifieddate();

	/**
	 * Sets the modifieddate of this assetlistentry.
	 *
	 * @param modifieddate the modifieddate of this assetlistentry
	 */
	public void setModifieddate(Date modifieddate);

	/**
	 * Returns the assetlistentrykey of this assetlistentry.
	 *
	 * @return the assetlistentrykey of this assetlistentry
	 */
	@AutoEscape
	public String getAssetlistentrykey();

	/**
	 * Sets the assetlistentrykey of this assetlistentry.
	 *
	 * @param assetlistentrykey the assetlistentrykey of this assetlistentry
	 */
	public void setAssetlistentrykey(String assetlistentrykey);

	/**
	 * Returns the title of this assetlistentry.
	 *
	 * @return the title of this assetlistentry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this assetlistentry.
	 *
	 * @param title the title of this assetlistentry
	 */
	public void setTitle(String title);

	/**
	 * Returns the type_ of this assetlistentry.
	 *
	 * @return the type_ of this assetlistentry
	 */
	public int getType_();

	/**
	 * Sets the type_ of this assetlistentry.
	 *
	 * @param type_ the type_ of this assetlistentry
	 */
	public void setType_(int type_);

	/**
	 * Returns the assetentrysubtype of this assetlistentry.
	 *
	 * @return the assetentrysubtype of this assetlistentry
	 */
	@AutoEscape
	public String getAssetentrysubtype();

	/**
	 * Sets the assetentrysubtype of this assetlistentry.
	 *
	 * @param assetentrysubtype the assetentrysubtype of this assetlistentry
	 */
	public void setAssetentrysubtype(String assetentrysubtype);

	/**
	 * Returns the assetentrytype of this assetlistentry.
	 *
	 * @return the assetentrytype of this assetlistentry
	 */
	@AutoEscape
	public String getAssetentrytype();

	/**
	 * Sets the assetentrytype of this assetlistentry.
	 *
	 * @param assetentrytype the assetentrytype of this assetlistentry
	 */
	public void setAssetentrytype(String assetentrytype);

	/**
	 * Returns the lastpublishdate of this assetlistentry.
	 *
	 * @return the lastpublishdate of this assetlistentry
	 */
	public Date getLastpublishdate();

	/**
	 * Sets the lastpublishdate of this assetlistentry.
	 *
	 * @param lastpublishdate the lastpublishdate of this assetlistentry
	 */
	public void setLastpublishdate(Date lastpublishdate);

}