/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package serviceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Menus service. Represents a row in the &quot;LT_Menus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>serviceBuilder.model.impl.MenusModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>serviceBuilder.model.impl.MenusImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Menus
 * @generated
 */
@ProviderType
public interface MenusModel extends BaseModel<Menus> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a menus model instance should use the {@link Menus} interface instead.
	 */

	/**
	 * Returns the primary key of this menus.
	 *
	 * @return the primary key of this menus
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this menus.
	 *
	 * @param primaryKey the primary key of this menus
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this menus.
	 *
	 * @return the uuid of this menus
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this menus.
	 *
	 * @param uuid the uuid of this menus
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this menus.
	 *
	 * @return the ID of this menus
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this menus.
	 *
	 * @param id the ID of this menus
	 */
	public void setId(String id);

	/**
	 * Returns the created date of this menus.
	 *
	 * @return the created date of this menus
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this menus.
	 *
	 * @param createdDate the created date of this menus
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this menus.
	 *
	 * @return the modified date of this menus
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this menus.
	 *
	 * @param modifiedDate the modified date of this menus
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the created user of this menus.
	 *
	 * @return the created user of this menus
	 */
	@AutoEscape
	public String getCreatedUser();

	/**
	 * Sets the created user of this menus.
	 *
	 * @param createdUser the created user of this menus
	 */
	public void setCreatedUser(String createdUser);

	/**
	 * Returns the modified user of this menus.
	 *
	 * @return the modified user of this menus
	 */
	@AutoEscape
	public String getModifiedUser();

	/**
	 * Sets the modified user of this menus.
	 *
	 * @param modifiedUser the modified user of this menus
	 */
	public void setModifiedUser(String modifiedUser);

	/**
	 * Returns the code of this menus.
	 *
	 * @return the code of this menus
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this menus.
	 *
	 * @param code the code of this menus
	 */
	public void setCode(String code);

	/**
	 * Returns the display name of this menus.
	 *
	 * @return the display name of this menus
	 */
	@AutoEscape
	public String getDisplayName();

	/**
	 * Sets the display name of this menus.
	 *
	 * @param displayName the display name of this menus
	 */
	public void setDisplayName(String displayName);

	/**
	 * Returns the description of this menus.
	 *
	 * @return the description of this menus
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this menus.
	 *
	 * @param description the description of this menus
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this menus.
	 *
	 * @return the url of this menus
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this menus.
	 *
	 * @param url the url of this menus
	 */
	public void setUrl(String url);

	/**
	 * Returns the func of this menus.
	 *
	 * @return the func of this menus
	 */
	@AutoEscape
	public String getFunc();

	/**
	 * Sets the func of this menus.
	 *
	 * @param func the func of this menus
	 */
	public void setFunc(String func);

	/**
	 * Returns the type of this menus.
	 *
	 * @return the type of this menus
	 */
	public int getType();

	/**
	 * Sets the type of this menus.
	 *
	 * @param type the type of this menus
	 */
	public void setType(int type);

	/**
	 * Returns the is active of this menus.
	 *
	 * @return the is active of this menus
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this menus is is active.
	 *
	 * @return <code>true</code> if this menus is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this menus is is active.
	 *
	 * @param isActive the is active of this menus
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the parent ID of this menus.
	 *
	 * @return the parent ID of this menus
	 */
	@AutoEscape
	public String getParentId();

	/**
	 * Sets the parent ID of this menus.
	 *
	 * @param parentId the parent ID of this menus
	 */
	public void setParentId(String parentId);

}